### ISSUE TITLE
HighStock Navigator empty

### ISSUE THREAD

**Issue by mkeuschn** [pablojim/highcharts-ng#129]
Hi the Navigator part of the highstock chart is empty.

![navigatorempty](https://cloud.githubusercontent.com/assets/4345006/3080439/38c47450-e4b0-11e3-941a-b5978bfcc92f.png)

Javascript Error:

``` javascript
TypeError: Cannot read property 'length' of undefined
    at Object.yb.updatedDataHandler (http://localhost:49434/Scripts/Highstock/highstock.js:354:171)
    at Object.jQuery.event.dispatch (http://localhost:49434/Scripts/jquery-1.10.2.js:5109:9)
    at Object.elemData.handle (http://localhost:49434/Scripts/jquery-1.10.2.js:4780:46)
    at Object.jQuery.event.trigger (http://localhost:49434/Scripts/jquery-1.10.2.js:5021:12)
    at Object.<anonymous> (http://localhost:49434/Scripts/jquery-1.10.2.js:5705:17)
    at Function.jQuery.extend.each (http://localhost:49434/Scripts/jquery-1.10.2.js:671:23)
    at jQuery.fn.jQuery.each (http://localhost:49434/Scripts/jquery-1.10.2.js:280:17)
    at jQuery.fn.extend.trigger (http://localhost:49434/Scripts/jquery-1.10.2.js:5704:15)
    at W.HighchartsAdapter.W.HighchartsAdapter.a.fireEvent (http://localhost:49434/Scripts/Highstock/highstock.js:25:345)
    at Object.L.redraw (http://localhost:49434/Scripts/Highstock/highstock.js:246:188) 
```

**Comment by louixs** [comment]
@chrisleavoy are you still getting an empty navigator?
