### ISSUE TITLE
Breaking rawgit.com/pablojim/highcharts-ng/master/dist/highcharts-ng.js

### ISSUE THREAD

**Issue by asimnzr** [pablojim/highcharts-ng#366]
Hi,

Reference from https://rawgit.com/pablojim/highcharts-ng/master/dist/highcharts-ng.js is breaking with:

TypeError: Unable to get property 'min' of undefined or null reference
   at deepExtend (https://rawgit.com/pablojim/highcharts-ng/master/dist/highcharts-ng.js:115:13)
   at Anonymous function (https://rawgit.com/pablojim/highcharts-ng/master/dist/highcharts-ng.js:175:11)
   at forEach (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.js:323:11)
   at getMergedOptions (https://rawgit.com/pablojim/highcharts-ng/master/dist/highcharts-ng.js:173:7)
   at initChart (https://rawgit.com/pablojim/highcharts-ng/master/dist/highcharts-ng.js:347:11)
   at res.link (https://rawgit.com/pablojim/highcharts-ng/master/dist/highcharts-ng.js:366:9)
   at Anonymous function (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.js:8252:34)
   at invokeLinkFn (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.js:8258:9)
   at nodeLinkFn (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.js:7768:11)
   at compositeLinkFn (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15

Bad update or?

Asim

**Comment by pablojim** [comment]
I can't see that error. See: http://jsfiddle.net/qhqydzde/

**Comment by asimnzr** [comment]
Looks like the difference is rawgit vs rawgithub:
https://rawgithub.com/pablojim/highcharts-ng/master/dist/highcharts-ng.js
https://rawgit.com/pablojim/highcharts-ng/master/dist/highcharts-ng.js

**Comment by pablojim** [comment]
Still not seeing an error: http://jsfiddle.net/0pdkm0nm/

**Comment by jvandyke** [comment]
I can confirm the same issue with 0.0.9 and Highcharts 4.0.3. This was not an issue with 0.0.8. I am pulling using npm.

**Comment by TheSharpieOne** [comment]
This is related to #367 and resolved by #369

**Comment by pablojim** [comment]
close #369
