### ISSUE TITLE
noticed breakage with updated version of highstocks

### ISSUE THREAD

**Issue by estrabd** [pablojim/highcharts-ng#376]
The recently updated http://code.highcharts.com/stock/highstock.js broke my deployment, and I had to force it to use the older version at http://code.highcharts.com/stock/1.2.5/highstock.js:

ReferenceError: Highcharts is not defined
    at initChart (js/highcharts-ng.js:259:17)
    at link (js/highcharts-ng.js:270:9)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:62:364
    at J (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:52:492)
    at h (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:46:28)
    at h (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:46:45)
    at h (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:46:45)
    at h (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:46:45)
    at J (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:52:433)
    at h (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js:46:28) <div id="chart1" config="chartConfig" class="span9 ng-isolate-scope">

**Comment by pablojim** [comment]
I'm not seeing this issue: http://jsfiddle.net/r88yszk0/128/ Could you show a demonstration?
