### ISSUE TITLE
Highcharts[chartType] is not a function

### ISSUE THREAD

**Issue by asso1985** [pablojim/highcharts-ng#411]
Hello, so here's my weird situation:
As you can see basically the code below is the example code form the github page in order to get a highstoke chart.

In my config : 

    highchartsNGProvider.lazyLoad([highchartsNGProvider.HIGHSTOCK]);
   

In my controller:

    var initChart = function() {
    $scope.chartConfig = {
        options: {
            chart: {
                zoomType: 'x'
            },
            rangeSelector: {
                enabled: true
            },
            navigator: {
                enabled: true
            }
        },
        series: [],
        title: {
            text: 'Hello'
        },
        useHighStocks: true,
    }

    $scope.chartConfig.series.push({
        id: 1,
        data: [
            [1147651200000, 23.15],
            [1147737600000, 23.01],
            [1147824000000, 22.73],
            [1147910400000, 22.83],
            [1147996800000, 22.56],
            [1148256000000, 22.88],
            [1148342400000, 22.79],
            [1148428800000, 23.50],
            [1148515200000, 23.74],
            [1148601600000, 23.72],
            [1148947200000, 23.15],
            [1149033600000, 22.65]
        ]
    },   {
        id: 2,
        data: [
            [1147651200000, 25.15],
            [1147737600000, 25.01],
            [1147824000000, 25.73],
            [1147910400000, 25.83],
            [1147996800000, 25.56],
            [1148256000000, 25.88],
            [1148342400000, 25.79],
            [1148428800000, 25.50],
            [1148515200000, 26.74],
            [1148601600000, 26.72],
            [1148947200000, 26.15],
            [1149033600000, 26.65]
        ]

    }

    );
    }

    highchartsNG.ready(function(){
      initChart();
    }, this)

The html : 
   &lt;highchart id="chart-fluidity" config="chartConfig" style="height: 350px; min-width: 310px"&gt;
   &lt;/highchart&gt;

Here's the error a get : 

 TypeError: Highcharts[chartType] is not a function
    at initChart (http://localhost:3000/bower_components/highcharts-ng/dist/highcharts-ng.js:362:19)
    at res.link (http://localhost:3000/bower_components/highcharts-ng/dist/highcharts-ng.js:377:9)
    at http://localhost:3000/bower_components/highcharts-ng/dist/highcharts-ng.js:497:19
    at Object.ready (http://localhost:3000/bower_components/highcharts-ng/dist/highcharts-ng.js:48:11)
    at res.link (http://localhost:3000/bower_components/highcharts-ng/dist/highcharts-ng.js:496:27)
    at http://localhost:3000/bower_components/angular/angular.js:8275:44
    at invokeLinkFn (http://localhost:3000/bower_components/angular/angular.js:8281:9)
    at nodeLinkFn (http://localhost:3000/bower_components/angular/angular.js:7791:11)
    at compositeLinkFn (http://localhost:3000/bower_components/angular/angular.js:7140:13)
    at compositeLinkFn (http://localhost:3000/bower_components/angular/angular.js:7143:13) <div id="chart-fluidity" config="chartConfig" style="height: 350px; min-width: 310px" class="ng-isolate-scope">

And here's a screenshot of my net filtered by "high"

![screen shot 2015-11-21 at 15 22 48](https://cloud.githubusercontent.com/assets/1164569/11318859/ff8e5492-9063-11e5-9aad-8866707d80eb.png)

**Comment by asso1985** [comment]
Seems like : 
   highchartsNGProvider.lazyLoad([highchartsNGProvider.HIGHSTOCK]);

Is not workng, still loading highchart not highstock. 

Can't fix the issue still.

**Comment by rushlinneu** [comment]
bower install highcharts-ng

Add references to Highcharts/Highstocks:
according to the doc, you should include
<script src="http://code.highcharts.com/stock/highstock.src.js"></script>
instead of
<script src="http://code.highcharts.com/highcharts.src.js"></script>
in your index.html
