### ISSUE TITLE
 Highcharts error #18: www.highcharts.com/errors/18

### ISSUE THREAD

**Issue by Sirish3** [pablojim/highcharts-ng#544]
Console:

angular.min.js:107 Error: Highcharts error #18: www.highcharts.com/errors/18
    at Object.H.error (http://localhost:8080/tcm_portal_web_six/tpim-html5/app/bower_components/highcharts/highcharts.src.js:102:23)
    at http://localhost:8080/tcm_portal_web_six/tpim-html5/app/bower_components/highcharts/highcharts.src.js:16372:27
    at Array.forEach (native)
    at H.each (http://localhost:8080/tcm_portal_web_six/tpim-html5/app/bower_components/highcharts/highcharts.src.js:1601:44)
    at object.bindAxes (http://localhost:8080/tcm_portal_web_six/tpim-html5/app/bower_components/highcharts/highcharts.src.js:16348:17)
    at object.init (http://localhost:8080/tcm_portal_web_six/tpim-html5/app/bower_components/highcharts/highcharts.src.js:16246:24)
    at object.init (http://localhost:8080/tcm_portal_web_six/tpim-html5/app/bower_components/highcharts/highcharts.src.js:19864:39)
    at H.Chart.initSeries (http://localhost:8080/tcm_portal_web_six/tpim-html5/app/bower_components/highcharts/highcharts.src.js:14324:24)
    at http://localhost:8080/tcm_portal_web_six/tpim-html5/app/bower_components/highcharts/highcharts.src.js:18632:40
    at H.fireEvent (http://localhost:8080/tcm_portal_web_six/tpim-html5/app/bower_components/highcharts/highcharts.src.js:1804:17)

My chartConfig is simple:

$scope.chartConfig = {
       yAxis:[{
            title:{                
                text:"yAxis working"
            }    
        },
        {
            title:{                
                text:"yAxis2 working"
            }    
        }], 
        series:[
            {
                data:[1,2,3,4,5],
                yAxis: 0
            },
            {   data:[5,3,2,1,4],
            		yAxis: 1
            }
        ] 
       };

My Libraries:

<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js"></script>
Highcharts JS v5.0.6
highcharts-ng.js latest one.

The issue is not reproducible in jsfiddle/plunker.

Only happening in my wokspace .no clue whats happening. 

Thanks in Advance.

**Comment by pablojim** [comment]
@Sirish3 could you try the latest version and create a jsfiddle if you are still having a problem.
