### ISSUE TITLE
jsfiddle basic example throws error: Uncaught Error: [$injector:modulerr] Failed to instantiate module myapp

### ISSUE THREAD

**Issue by mathiasconradt** [pablojim/highcharts-ng#568]
When cloning the repo and open the jsfiddles/basic/demo.html, the following JS error is thrown in the Chrome developer console:

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module myapp due to:
Error: [$injector:nomod] Module 'myapp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.8/$injector/nomod?p0=myapp
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:68:12
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:2082:17
    at ensure (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:2006:38)
    at module (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:2080:14)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:4617:22
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:321:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:4601:5)
    at createInjector (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:4523:19)
    at doBootstrap (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:1758:20)
    at bootstrap (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:1779:12)
http://errors.angularjs.org/1.5.8/$injector/modulerr?p0=myapp&p1=Error%3A%2….googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A1779%3A12)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:68:12
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:2082:17
    at ensure (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:2006:38)
    at module (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:2080:14)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:4617:22
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:321:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:4601:5)
    at createInjector (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:4523:19)
    at doBootstrap (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:1758:20)
    at bootstrap (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:1779:12)
http://errors.angularjs.org/1.5.8/$injector/modulerr?p0=myapp&p1=Error%3A%2….googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.8%2Fangular.js%3A1779%3A12)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:68:12
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:4640:15
    at forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:321:20)
    at loadModules (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:4601:5)
    at createInjector (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:4523:19)
    at doBootstrap (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:1758:20)
    at bootstrap (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:1779:12)
    at angularInit (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:1664:5)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:31763:5
    at HTMLDocument.trigger (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js:3207:7)
```

It works fine when I remove the surround `$(function () {` and `})` from the JS code.

**Comment by pablojim** [comment]
Seems to work fine here: http://jsfiddle.net/gh/get/jquery/3.1.1/pablojim/highcharts-ng/tree/master/jsfiddles/basic/

**Comment by mathiasconradt** [comment]
Ok, now I see. 
It only works in jsfiddle if you include the JS libraries in the html file

```
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.js"></script>
<script src="https://rawgithub.com/pablojim/highcharts-ng/master/src/highcharts-ng.js"></script>
<script src="https://code.highcharts.com/stock/highstock.src.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
```

If you use the jsfiddle external resources functionality (https://snag.gy/4mvKJg.jpg), then it does not work andI get the error. And it also does not work if I open the demo.html locally in Chrome (via file://)
