### ISSUE TITLE
Ajax example

### ISSUE THREAD

**Issue by jvvlimme** [pablojim/highcharts-ng#6]
Is there any way to get an example where the data is loaded in with $http?   I'm trying this but keep getting following error:

TypeError: Object #<Object> has no method 'forEach'
    at ensureIds (http://localhost:3000/js/highcharts-ng.js:7:20)
    at Object.fn (http://localhost:3000/js/highcharts-ng.js:51:25)
    at Object.Scope.$digest (http://code.angularjs.org/1.1.0/angular.js:7705:27)
    at Object.Scope.$apply (http://code.angularjs.org/1.1.0/angular.js:7899:24)
    at done (http://code.angularjs.org/1.1.0/angular.js:8891:20)
    at completeRequest (http://code.angularjs.org/1.1.0/angular.js:9035:7)
    at XMLHttpRequest.xhr.onreadystatechange (http://code.angularjs.org/1.1.0/angular.js:9001:11) 

I'm new to angular so it's likely it's something I'm doing wrong but I can't seem to figure it out myself.

**Comment by Rafi993** [comment]
first assign a temporary chart config object to the chart so that it does not throw error then when the request has arrived assign the new chart config to the chart. It is better to form the complete config object at server side if possible to make chart rendering fast as possible.

<highchart id="chart1" config="chartConfig"></highchart>


```
$scope.chartConfig = {  //assign some temporary chart config so that it does not throw error }   

api.post(postbody).then(function(data){
   $scope.chartConfig = data;
})

```

please close the issue if it is sloved @jvvlimme
